export = {
  AnimeEx: {
    props: {
      aid: '1',
      eps: '13',
      count: '13',
      special_count: '3',
      year: '1999-1999',
      type: 'TV Series',
      romaji: 'Seikai no Monshou',
      kanji: '?????',
      english: 'Crest of the Stars',
      other: '?????\'Crest of the Stars',
      short_names: 'CotS\'SnM',
      synonyms: 'Hv?zdn? erb\'?????',
      // eslint-disable-next-line max-len
      cat_list: 'Space,Plot Continuity,Future,Space Travel,Sci-Fi,Other Planet,Action,Genetic Modification,Novel,War,Shipboard,Slow When It Comes to Love,Military,Romance,Human Enhancement,Large Breasts,Gunfights,Adventure,Nudity,Small Breasts',
    },
    propNames: [
      'aid',
      'eps',
      'count',
      'special_count',
      'year',
      'type',
      'romaji',
      'kanji',
      'english',
      'other',
      'short_names',
      'synonyms',
      'cat_list',
    ],
    propValues: [
      '1',
      '13',
      '13',
      '3',
      '1999-1999',
      'TV Series',
      'Seikai no Monshou',
      '?????',
      'Crest of the Stars',
      '?????\'Crest of the Stars',
      'CotS\'SnM',
      'Hv?zdn? erb\'?????',
      // eslint-disable-next-line max-len
      'Space,Plot Continuity,Future,Space Travel,Sci-Fi,Other Planet,Action,Genetic Modification,Novel,War,Shipboard,Slow When It Comes to Love,Military,Romance,Human Enhancement,Large Breasts,Gunfights,Adventure,Nudity,Small Breasts',
      // '915321600',
      // '922579200',
      // '16',
      // '0',
      // '224618.jpg',
    ],
  },
};
